apiVersion: 1

datasources:

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: '15s'

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000

  - name: Marquez-DB
    type: postgres
    access: proxy
    url: marquez-db:5432
    database: marquez
    user: grafana_reader
    secureJsonData:
      password: grafana123
    jsonData:
      sslmode: disable
      postgresVersion: 1400
